blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.create_item, name='add'),
    path('<int:item_id>/', views.detail, name='detail'),
    path('search/', views.search_venues, name='search-venues'),
    path('card/', views.card, name='card')

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

blog/models.py
from django.db import models


# Create your models here.
class Item(models.Model):
    def __str__(self):
        return self.item_head

    item_head = models.CharField(max_length=50)
    item_title = models.CharField(max_length=50)
    item_descript = models.CharField(max_length=500)

blog/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_head', 'item_title', 'item_descript']

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from .forms import ItemForm
from .models import Item


# Create your views here.

def index(request):
    all_items = Item.objects.all()

    unique_items = set()

    item_list = []
    for item in all_items:
        if item.item_head not in unique_items:
            unique_items.add(item.item_head)
            item_list.append(item)
    ######################

    template = loader.get_template('blog/index.html')
    context = {
        'item_list': item_list,

    }

    return HttpResponse(template.render(context, request))


def card(request):
    item_list = Item.objects.all()
    template = loader.get_template('blog/card.html')
    context = {
        'item_list': item_list,

    }
    return HttpResponse(template.render(context, request))


def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('blog:index')

    return render(request, 'blog/item-form.html', {'form': form})


def detail(request, item_id):
    sections = Item.objects.get(pk=item_id)
    item_list = Item.objects.filter(item_head=sections)

    context = {
        'item_list': item_list,
    }

    return render(request, 'blog/detail.html', context)


def search_venues(request):
    if request.method == "POST":
        searched = request.POST['searched']
        venues = Item.objects.filter(item_head=searched)
        context = {
            'searched': searched,
            'venues': venues,
        }
        return render(request, 'blog/search.html', context)
    else:
        context = {

        }
        return render(request, 'blog/search.html', context)

blog/templates/blog/Index.html
{% extends 'blog/base.html' %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta http-equiv="Content-Type" content="charset=UTF-8">

    <title>Home</title>
</head>

<body>
{% block body %}
<div class="container">
        <header>
            <div>
                <h1>
                    science <span class="speacial">Team</span>
                </h1>
            </div>
            <div class="sign">
                <button class="sign-up"> sign up</button>
                <button class="login">Log In</button>
            </div>
        </header>

        <!-- -------------------the fixed aside------------ -->
        <aside>

            <div class="theme-toggler">
                <span class="fas fa-moon active-theme"></span>
                <span class="fas fa-sun "></span>
            </div>

            <!-- --------------------- -->

            <div class="social-links">
                <span class="fa-brands fa-facebook"></span>
                <span class="fa-brands fa-twitter"></span>
                <span class="fa-brands fa-instagram"></span>
            </div>

            <div class="other-links">
                <span class="fa fa-share-alt" aria-hidden="false"></span>
                <span class="fa fa-info-circle" aria-hidden="false"></span>
            </div>
        </aside>
        <!-- ------------------sidebar menu links ----------------- -->

        <!-- -------------------Home Interface---------------- -->
        <div class="interface">
      <div class="content">
                <small>Welcome to our </small>
                <h1>community</h1>
                <button class="btn-success">Know Who We Are</button>
            </div>
            <form method="post" action="{% url 'blog:search-venues' %}">
                {% csrf_token %}
                <div class="search-input">
                    <input type="search" name="searched" id="search" placeholder="Search">
                </div>
                <button type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
           </form>


        <div class="pages-btns-styles">
            <a href="{% url 'blog:add'%}" class="btn btn-success">+</a>
            {% for item in item_list %}

                <a href="{% url 'blog:detail' item.id %}" class="btn btn-success">{{item.item_head}}</a>
            {% endfor %}

        </div>



<a href="{% url 'blog:card' %}" >card</a>

        </div>
<!-- end interface -->





    </div>



<a class="scroll-top " id="scroll-top">
    <i class="fa fa-arrow-up"></i>
</a>


{% endblock %}
</body>

</html>

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    <link rel="stylesheet" href="{% static 'blog/all.min.css' %}">

    <script src="{%static 'blog/jsindex.js'%}"></script>
    <title>Title</title>
</head>
<body>


    {% block body%}
    {% endblock %}
</body>
</html>

blog/templates/blog/card.html
{% extends 'blog/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block body %}

{% for venue in item_list %}
<div class="container ">
        <div class="row">
            <div class="card col">
                <div class="card-header">
                   <div class="card-brand">
                    <h2> {{venue.item_title}}</h2>
                    <i class="fa fa-link"></i>
                   </div>
                    <span class="badge">{{venue.item_head}}</span>
                </div>
                <div class="card-content">
                    <p >
                        {{venue.item_descript}}
                    </p>

                    <div>
                    </div>
                </div>
                <div class="card-footer">
                    <span class="badge">chat</span>
                    <i class="fa fa-heart" style="font-size: 20px;"></i>
                </div>
            </div>


        </div>
    </div>
{% endfor %}

{% endblock %}
</body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block body %}

{% for venue in item_list %}
<div class="container ">
        <div class="row">
            <div class="card col">
                <div class="card-header">
                   <div class="card-brand">
                    <h2> {{venue.item_title}}</h2>
                    <i class="fa fa-link"></i>
                   </div>
                    <span class="badge">{{venue.item_head}}</span>
                </div>
                <div class="card-content">
                    <p >
                        {{venue.item_descript}}
                    </p>

                    <div>
                    </div>
                </div>
                <div class="card-footer">
                    <span class="badge">chat</span>
                    <i class="fa fa-heart" style="font-size: 20px;"></i>
                </div>
            </div>


        </div>
    </div>
{% endfor %}

{% endblock %}

</body>
</html>

blog/templates/blog/item-form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'blog/styleform.css' %}">
    <title>Title</title>
</head>
<body>

      <div class="row">
          <div class="col-md-3 offset-md-2">
              <form method="POST">
                  {% csrf_token%}
                  {{form}}
                  <button type="submit">add</button>
              </form>
          </div>
      </div>
{% block body%}
    {% endblock %}
</body>
</html>

blog/templates/blog/search.html
{% extends 'blog/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block body %}
{% if searched %}

{% for venue in venues %}
<div class="container ">
        <div class="row">
            <div class="card col-md-6">
                <div class="card-header col-md-3">
                   <div class="card-brand col-md-2">
                    <h2> {{venue.item_title}}</h2>
                    <i class="fa fa-link"></i>
                   </div>
                    <span class="badge">{{searched}}</span>
                </div>
                <div class="card-content">
                    <p >
                        {{venue.item_descript}}
                    </p>

                    <div>
                    </div>
                </div>
                <div class="card-footer">
                    <span class="badge">chat</span>
                    <i class="fa fa-heart" style="font-size: 20px;"></i>
                </div>
            </div>


        </div>
    </div>
    </div>
{% endfor %}
{% else %}
<h4>Error while searching</h4>
<a class="scroll-top " id="scroll-top">
    <i class="fa fa-arrow-up"></i>
</a>
{% endif %}

{% endblock %}


</body>
</html>